### ISSUE TITLE
Dynamic requires in executable

### ISSUE THREAD

**Issue by sharathbaddam** [zeit/pkg#127]
Hello,

I bundled all my code into an executable, from the executable i'm requiring an app.js file (stored in different directory) dynamically through a config file. I have few require statements in the app.js that require few node_modules. Those node_modules are already bundled into executable. But app.js would still need all the modules locally in node_modules directory. I think this is how node works. 

My question is, can an we make an executable with pkg where an external file like app.js wouldn't need local node_modules directory ?

any help is appreciated.

**Comment by igorklopov** [comment]
Most simple solution is to register a global require function that works from inside executable.
```
global.require2 = require;
```
Place that line to entrypoint file of your application, before you call external `app.js`. On the other hand, in `app.js` use `require2` instead of `require`. Is it acceptable? Btw it is really necessary even for non-pkg mode, because you can have `app.js` without `node_modules` around.

**Comment by sharathbaddam** [comment]
Yes, it worked!!!
Thanks for the help!
