### ISSUE TITLE
Abbility to use other version than v7,v8,etc

### ISSUE THREAD

**Issue by mkg20001** [zeit/pkg#171]
Currently I haven't found a way to use a version like v8.2.1
Is that possible?

**Comment by nmchau** [comment]
I have the same problem....
According to the document, if we don't specify the target node version, then the latest version will be applied... So the version should have been v8.2.1 in this case instead of v8.0.0?

**Comment by dizlexik** [comment]
I'm definitely interested in this too.

I posted a similar question to Slack a few days ago but didn't get an answer:
https://zeit-community.slack.com/messages/C57C53R6K/p1500653904026892
> Is it true that pkg can only produce binaries with Node versions that exist here?
> https://github.com/zeit/pkg-fetch/blob/master/patches/patches.json
> 
> If I wanted to target Node 8.2.1 I would not be able to do that until a patch exists for it, correct?

**Comment by igorklopov** [comment]
@dizlexik Please wait for new pkg release

**Comment by igorklopov** [comment]
Please try `pkg@4.1.4` and pass something like `-t node8.2.1` to pkg command line.

**Comment by dizlexik** [comment]
Thanks, that's great.

But just to clarify, as I understand it any new Node version that comes out will require some amount of work from you to create a corresponding patch before it can be used with pkg. So there will always be some lag time between Node release and pkg support, even in the case of an important security patch. Is there any guarantee on the timeframe between Node release and pkg supporting it or does it depend more on when you have the free time to work on it?

Also I would love to use this in production so I'm wondering what the plan is regarding ongoing releases. Is there a plan in place to make sure this project lives on for the years to come, or is there a chance that releases may stop suddenly without warning at some point? It's a Zeit project so I'm inclined to think you guys have thought this all through since you're awesome like that, but I just wanted to make sure and was wondering if this is documented anywhere. Thanks!

**Comment by igorklopov** [comment]
There is upcoming solution to use original `node` binary instead of patched one. Stay tuned!
