### ISSUE TITLE
Android and IOS support

### ISSUE THREAD

**Issue by rlaurente** [zeit/pkg#288]
Is there a way I can run the executable in android and IOS ?

I tried this in android "pkg -t latest-linux-x64 .", then I copy in android and execute.

It says "not executable: 64-bit ELF file"

Thanks

**Comment by simonhochrein** [comment]
Android and IOS are almost always on a ARMv7 or ARMv6 architecture.

**Comment by dcerisano** [comment]
This is astounding. Are you saying pkg will build native Android and iOS binaries? Why are these platforms not mentioned in the docs?

It would be awesome if there were an option to produce APKs and IPAs!

**Comment by danielgindi** [comment]
You can't. An APK needs to be aware of the Java runtime and the Android OS itself, and an IPA needs to be aware of iOS and use its APIs.
As a `node` app is not a UI app, you have nothing to do with it on iOS, as the apps are UI centric. You can't install a service on iOS either, simply because you don't have the permissions to do so.

On both iOS and Android, if you would try to run the pkg output on a jailbroken device - it might just work as it's a linux underneath. But on the higher level of the OS it just won't work.

**Comment by dcerisano** [comment]
That may be true for iOS, but certainly not for Android.

I have deployed Android services bundled with JXCORE that run nodejs modules. These were so successful they were actually pulled from the Play Store, since they used nodejs to implement Torrent swarms.

The "higher level" concerns to be aware of are actually policy concerns around security, not any specific OS, since there is always a path around technology limitations.

**Comment by dcerisano** [comment]
Statements like "You cant." and "It just won't work." are meaningless in computer science, unless you are claiming this is an NP-Complete problem and also intractable. If you have proof, I would urge you to claim the $1M bounty.

I have deployed mobile services bundled with JXCORE. These were so successful they were actually pulled from the mobile market, since they used opensource nodejs modules to implement Torrent swarms.

The "higher level" domain to be aware of is actually market policy compliance, not any specific OS, since there is always a path to extend low level OS limitations. The Linux kernels used by mobile OSes like Android and iOS are especially designed to encourage such extensions.

**Comment by danielgindi** [comment]
There's no need to be so haughty, it just doesn't get you anywhere.

Okay, so let's be more specific: "The OSes won't let you".
These binaries do not only have to be signed inside a package (APK/IPA), but they have to "talk" to the higher level API, and present some kind of high level component.
Node.js/Pkg do not have any knowledge of these components.

For example - in iOS - when an app loads, it expects a `UIWindow` to be created. If a `UIWindow` is not created, the OS throws an error and kicks your ass. OR you could register as an extension - i.e. for the keyboard or watch. But again, Node.js does not know how to do that. It has to import iOS libraries to do so.
On the Android, you have to create a service or an activity, or at least an `android.app.Application` instance.

Again, you *could* run on both platforms, if you jailbroke them and deployed them manually.

Of course "there is always a path to extend low level OS limitation", but that is not something that pkg will be able to do for you out of the box, and will most probably be meaningless anyway.
As in iOS an app downloaded from the AppStore must present *some kind* of a UI, even if it's just a keyboard extension, and a Node.js is *not* a UI framework/client/whatever.
On Android it will make more sense, but will still be tough for people who do not have experience with low level Android apis, and binding NAN/NAPI to Node.js.

**Comment by dcerisano** [comment]
None of that has any bearing on on your claim that it cannot be done. Please try to remember there is always someone more clever than yourself.

**Comment by dcerisano** [comment]
None of that has any bearing on on your claim that it cannot be done without unauthorised hacks. Please try to remember there is always someone more clever than yourself.

**Comment by danielgindi** [comment]
@dcerisano not claiming to be clever, which I can't say about you.
It's more like apples and oranges.
You are looking at "is it scientifically possible/impossible". I'm practical, answering the "is it viable"/"does it make sense". And no, it does not make sense. No, it's not viable, especially not for iOS. As node.js is not a UI framework, there's no point in even going there and trying to make a valid IPA out of it. And in order to make it work as it should - as a background service - you have to do "unauthorised hacks".
There may be some kind of extreme-edge-case where that would make sense, but I can't think of any right now.

I'm sorry that I have to say this, but your attitude is not of someone who's trying to be helpful or even teach someone something useful. It's about being a smarty-pants. Picking on the letters, whether I can mathematically prove that that's impossible? Are you kidding me?
I mean, really, if you don't have something meaningful to say...

**Comment by rlaurente** [comment]
omg, I regret now why started this conversation lol

My only goal with this question is to run pkg inside cordova and run as a background service. There are good plugins now like nodejs-mobile to run node inside mobile app. I was also thinking it's possible for this to work too.

anyway, have a great day guys lol

Thanks

**Comment by danielgindi** [comment]
@rlaurente I'm not sure if running `node.js` *inside* an already running app is a good idea, as that could consume precious memory not available on a mobile device. But that has to be tested on a real world scenario.

By the way, remember talking about OSes not letting you do stuff? Here you might get into a problem where Apple won't let you do stuff. Apple's guidelines say that you can't bring a JIT compiler to iOS, and node.js is V8. You would have to compile it against JavaScriptCore somehow.

But hey, if there already is a plugin that allows you to run in inside your app, why use pkg? I mean it's a completely different use case to package it as a standalone app, and combining into an existing app that is packaged by Xcode/Gradle.

**Comment by rlaurente** [comment]
@danielgindi This is really funny because I even forgot what I'm experimenting that time, that I came up using pkg lol. It was like 8 months ago, and I surprise getting this replies lol

**Comment by danielgindi** [comment]
@rlaurente well experimentation with this stuff is always fun :-) I'm not a moderator of this repo but I think that if you don't remember the issue then it's time to close it 😆

**Comment by dcerisano** [comment]
The question has not been answered. Solutions involving authorised hacks are untenable.

**Comment by dcerisano** [comment]
The question has not been answered. Solutions involving authorised hacks are untenable.

**Comment by dcerisano** [comment]
he question has not been answered. Solutions involving unauthorised hacks are untenable.

**Comment by dcerisano** [comment]
The question has not been answered. Solutions involving unauthorised hacks are untenable.

**Comment by dcerisano** [comment]
The question has not been answered. Solutions involving unauthorised OS hacks are untenable. Hacking the application layer is also not an answer. 

Looking for an answer that is mobile market policy compliant without hacks.  iOS market policy does not allow apps to download scripts, so shrink-wrapped node applications are actually required.

**Comment by danielgindi** [comment]
@dcerisano In order to get `pkg` to work on iOS *and* be approved by Apple, you would have to compile node.js against JavascriptCore (and add a lot of JS polyfills, writing other implementations for native bindings etc.), or use it compiled against a JS interpreter, which apparently `nodejs-mobile` does (I haven't bumped into it before). 
Using it with an interpreter instead of a JIT will make it real slow.

I don't know if you have such a need, or how would you approach this, but as long as we're not using native modules I would write a thin layer that could allow Node.js scripts to work on JavascriptCore and its equivalent in other mobile platforms. It's all about the use case, and there are probably tens of different use cases, but I think that the most important core modules could be faked to with JavascriptCore, and some binding to the platform's native apis like `FileManager` etc.

Anyway there is a module that already does what he wants, which is `nodejs-mobile`, although not in the best way.

**Comment by dcerisano** [comment]
> `nodejs-mobile`  contains simulator strips will not be accepted on the App Store. Before trying to submit your application, it would be advisable to use the Release-iphoneos/NodeMobile.framework in your submission archive or strip the x64 slices from the universal framework's binaries before submitting.

**Comment by dcerisano** [comment]
That also does not answer  this question.

From the docs:
> `nodejs-mobile`  contains simulator strips will not be accepted on the App Store. Before trying to submit your application, it would be advisable to use the Release-iphoneos/NodeMobile.framework in your submission archive or strip the x64 slices from the universal framework's binaries before submitting.

It should also be possible to get `pkg` shrink-wrapped node applications submitted. Shrink-wrapped means they contain their own JS engine (node), with no external dependencies or further hackery required.

I have published mobile apps based on shrink-wrapped LUA, and the only caveat was they were not allowed to update their scripts at run-time.

So hopefully someone who has actually tried it will reply with their answer, or I shall blaze the trail myself.

**Comment by dcerisano** [comment]
That also does not answer  this question.

From the docs:
> `nodejs-mobile`  contains simulator strips will not be accepted on the App Store. Before trying to submit your application, it would be advisable to use the Release-iphoneos/NodeMobile.framework in your submission archive or strip the x64 slices from the universal framework's binaries before submitting.

It should also be possible to get `pkg` shrink-wrapped node applications submitted. Shrink-wrapped means they contain their own JS engine (node), with no external dependencies or further hackery required.

I have published mobile apps based on shrink-wrapped LUA, and the only caveats were they were not allowed to update their scripts at run-time, and they must run with only user permissions (no root).

So hopefully someone who has actually tried it will reply with their answer, or I shall jump through the fiery hoops myself.

**Comment by danielgindi** [comment]
Well up until recently Apple strictly rejected apps that brought a JIT compiler with them. That's the reason that there is no Chrome for iOS. (Well there is, but it's not real Chrome, it's Safari with Chrome's icon and some custom UI around it).
I can't seem to find any mention of it now in the Review Guidelines, so good luck!

**Comment by dcerisano** [comment]
Closed - lol.
