### ISSUE TITLE
[Feature Request] Add config for exclude scripts

### ISSUE THREAD

**Issue by jingsam** [zeit/pkg#303]
Suppose I have a `config.js` which specify db configurations and etc. This `config.js` would change frequently. So I want to tell `pkg` not packaging `config.js`, even through I require('./config') in source code.

**Comment by TooTallNate** [comment]
In short, you need to require the file with an absolute file path to avoid it from being bundled inside the binary. So that leads to the question of where do you want the `config.js` file to be read from on the filesystem. The places that would make most sense to me would be:

* Alongside where the binary lives:
   ```js
   require(process.execPath + '/config.js');
   ```
* From the current directory:
   ```js
   require(process.cwd() + '/config.js');
   ```

I hope that helps! Take a look at the [Snapshot filesystem docs](https://github.com/zeit/pkg#snapshot-filesystem) for more info.
