### ISSUE TITLE
[Q] how to set memory size option

### ISSUE THREAD

**Issue by hellower** [zeit/pkg#447]
node --max_old_space_size=4096 myAwesomeServer.js  

How can I add  (max_old_space_size) options to the pkg compression binary? 

cf. environment setting also not working
export NODE_OPTIONS="--max-old-space-size=2048"
./pkged_binary
Pkg: FLAGS_MISMATCH

**Comment by ataft** [comment]
For anyone that happens upon this issue, it's in the documentation here:
https://github.com/zeit/pkg#options

How would you do this for multiple options? 
Would it be like this `pkg app.js --options expose-gc max_old_space_size=4096`?

**Comment by jonface** [comment]
Can you confirm then that this is not possible to change at runtime?

That NODE_OPTIONS or any other way will not work, for example, if I don't want to bake 'max_old_space_size' into the binary, I want to change without needing to re-package.

Thanks

**Comment by aurelhann** [comment]
Any one can confirm that?
I could be great to increase max size limit at runtime and not at the build moment.

**Comment by albanm** [comment]
This is a really important point for me. I need to build the exec in a way that is compatible with low-resource machines, but allow extending memory on some more heavy-duty machines.

  - is it really impossible to define node options at runtime ?
  - if it is impossible, can it be changed by a modification of the code base (I am willing to work on a pull request) or is it too complicated because of the way pkg works ?

**Comment by yogeshbiz** [comment]
stuck on setting multiple options. does not works how ever tried. Ease any simple thing I am missing? 

pkg app.js --options max-old-space-size=256 tls-min-v1.0

actually there are more options I need to add

using SET NODE_OPTIONS=--max-old-space-size=256 --tls-min-v1.0
does not works at all with multiple options.
Single quote, double quote... all variations do not work.

The compiled EXE only picks up 1 option through NODE_OPTIONS
that means 1 option baked in EXE and 1 through NODE_OPTIONS. This is not enough.

Since #447 is closed, what was resolution?

**Comment by erossignon** [comment]
you can concatenate multiple options  (no space, comma seperated)

`pkg app.js --options max-old-space-size=256,tls-min-v1.0`

**Comment by yogeshbiz** [comment]
Thank you @erossignon. It worked. 

Without clue I spend 40+ hours in 3 days taking internet down with searches and lots of experiments, all permutations.
No body on any site, stackoverflow, opensource code search engines or blog while explaining --options, used multiple options, because no one has clue.

Please include this in [README ](https://github.com/vercel/pkg#options )file, options section.

**Comment by ilia-kebets-sonarsource** [comment]
Any solution for the initial question raised by https://github.com/vercel/pkg/issues/447#issue-332663187?

**Comment by ilia-kebets-sonarsource** [comment]
A hello-world app works for `pkg` prior to this change, I tried with v `5.6.0`:

hello.js
```js
const v8 = require('node:v8');
console.log('I have so much heap RAM:', v8.getHeapStatistics().total_available_size / 1024 / 1024 + ' MB');
```

Build binary: `./node_modules/.bin/pkg ./hello.js --targets=node16-macos-arm64`

Run it:

```bash
> ./hello
> I have so much heap RAM: 4140.093421936035 MB
> NODE_OPTIONS='--max-old-space-size=2048' ./hello
> I have so much heap RAM: 2092.093421936035 MB
```
