### ISSUE TITLE
“require('@arangodb').db;” can't be packaged

### ISSUE THREAD

**Issue by goldcode88** [zeit/pkg#464]
arangodb have two kinds of requires.
One is `const Database = require('arangojs').Database`, it's ok for pkg.
Another is `const db = require('@arangodb').db`, it returns error for pkg.

```
> Error! TypeError: Cannot read property '0' of null
    at shortFromAlias (/usr/local/lib/node_modules/pkg/lib-es5/walker.js:69:49)
    at Walker._callee5$ (/usr/local/lib/node_modules/pkg/lib-es5/walker.js:894:25)
    at tryCatch (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at <anonymous>
```

The following link is description about transaction code “require('@arangodb').db;”  in aragodb.
[](https://docs.arangodb.com/3.3/Manual/Appendix/JavaScriptModules/ArangoDB.html)

**Comment by pluma** [comment]
Hi @goldcode88,

I'm catching this one entirely by accident because I happen to be watching this repo but as an ArangoDB maintainer I can answer this:

`@arangodb` (and all modules in that namespace) is not a Node.js module, it's an ArangoDB module.

ArangoDB is not running on Node, it has its own embedded V8 JavaScript environment which aims to be generally compatible with Node.js (with some caveats).

I don't think `pkg` is useful for working with ArangoDB. I'm not sure what you're trying to do but if you just want to bundle your Foxx service into a single JS file, you can use webpack. You just need to use `require("@arangodb/locals").context` instead of `module.context`.

**Comment by pluma** [comment]
For the record: arangojs is the Node.js (and browser) *driver* for ArangoDB, so it is available on npm and works as a Node module. That is different.

**Comment by goldcode88** [comment]
Hi pluma,
    Thanks, I got it. ` arangodb.js `is different with `@arangodb`. `@arangodb` is not a Node.js module. It maybe is binary module. So pkg can't package it like a Node.js module.
As you said, if we use Foxx service, we don't need pkg tool. I had tried to use Foxx service last year, I found its' two drawbacks.(Maybe I misunderstood Foxx service).
1. It's can't support `websocket` communication. (`websocket` is important to my project);
2.It's a little difficult to debug.

From your explanation, I know `pkg` is difficult to package `@arangodb`. So I found a method to solve it.
I move all of microservices(use `@arangodb`) to Foxx service. Others continue to use `arangodb.js` microservices. `pkg` can package Others.

**Comment by pluma** [comment]
Yes, that sounds reasonable. We're working on the debuggability but the lack of support for websocket is a limitation of ArangoDB being a database rather than a general purpose platform like Node.js.

Splitting the code into a service and a Node.js app is a good solution.

**Comment by goldcode88** [comment]
Hi @pluma
Thanks again. I'll close the issue.  BTW，I'm curious for that it's http interface in the Internal implements of Foxx service or other methods. I want to know running efficiency between `Foxx service` and `arangojs` function for similar `aql` query.

**Comment by pluma** [comment]
@goldcode88 If you're just executing a single AQL query, it's probably slightly faster to use arangojs but if you're performing multiple operations (e.g. multiple AQL queries or CRUD operations) for one task, Foxx will come out ahead because it avoids a lot of overhead as Foxx runs inside ArangoDB itself.

**Comment by goldcode88** [comment]
@pluma I got it. Thanks again.
