### ISSUE TITLE
Error with external files read with fs.readFileSync are not included in pkg bundle

### ISSUE THREAD

**Issue by Ks89** [zeit/pkg#521]
Hi!

In my project I'm reading an external file (a private rsa key with extension .key) with this code:

```
fs.readFileSync('myfolder/my_private_key.key');
```
I'm able to build the project with pkg 4.3.4, but when I run the final binary file created by pkg I get this error:

```
    "Error: ENOENT: no such file or directory, open 'myfolder/my_private_key.key'",
    "    at Object.fs.openSync (fs.js:646:18)",
    "    at Object.fs.openSync (pkg/prelude/bootstrap.js:483:32)",
    "    at Object.fs.readFileSync (fs.js:551:33)",
    "    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:679:36)",
   (...)
```

If I copy this file next to the binary created by pkg, I can read it, otherwise no. So I suppose that It's not included in the final binary file created by pkg.

How can I fix this?

**Comment by Ks89** [comment]
fixed using 

```
const certPath = path.join(__dirname, '../myfolder/my_private_key.key');
const cert = fs.readFileSync(certPath);
```

and in my package.json I added:

```
"pkg": {
        "assets": [
            "public/**/*",
            "*.crt",
            "*.key"
        ],
        "targets": [
            "node8"
        ]
    },
```

**Comment by Jucesr** [comment]
@Ks89 how about using `fs.writeFile` I am getting an error

**Comment by Ks89** [comment]
I never tried, sorry

**Comment by Jucesr** [comment]
Well, I was able to fix it by reading the [docs](https://github.com/zeit/pkg#snapshot-filesystem).

I add a few line to the source code.
```js
//  Set the path of the project folder base on whether it is run with nodejs or as an executable
let project_folder;
if(process.pkg){
    //  It is run as an executable
    project_folder = path.dirname(process.execPath)
    
}else{
    //  It is run with nodejs
    project_folder = __dirname
}
```

Then I change the call to `fs.writeFile` to

```js 
fs.writeFile(path.join(project_folder, 'assets', 'my_image.png'))
```

**Comment by TomasHubelbauer** [comment]
This issue comes up on Google when searching for *node pkg error reading from file*. I get this error message when using `rcedit` with the generated Windows executable to set the executable icon. Prior to patching the executable's resources to set the icon, it works just fine as generated by PKG. After applying the icon resource, this error happens. There are some other links about this error online, but specifically related to PKG, this issue ranks the highest so I figured this information should go here. Also, it is kind of deceiving, but the icon is applied just fine to the binary, it's just that the rest of the binary is wrecked.

FWIW I have not found a better way to set the Windows executable icon.

**Comment by jeroen-van-dijk** [comment]
I got it fixed my listing the exact path in the `package.json`.

```
"pkg": {
        "scripts": "index.js",
        "assets": [
            "key_folder/server.key",
            "key_folder/server.cert"
        ],
        "outputPath": "dist"
    },
```
see https://github.com/vercel/pkg/issues/893#issuecomment-686441246
