### ISSUE TITLE
Does pkg compiling prevent source code from being extractable?

### ISSUE THREAD

**Issue by sisou** [zeit/pkg#69]
In the README you mention that scripts that are added as `scripts` in the config are compiled using the V8 compiler. Is that also true for regular dependencies that are found from the entry point?

And does this compilation prevent source code from being accessible in the package?

My use case here is, that I have a private key string in my source code, but when I ran `strings` on the resulting executable, the string was still there in plain text.

Thanks!

**Comment by igorklopov** [comment]
Imagine you create a simple C++ program, that outputs your key to stdout. If you compile it and look into executable, you will find your key inside it as well. The executable (created by pkg, or created by gcc) does not need to do anything with string literals (like your key) in order to use them at run time. String literals are stored as is. Application code is transformed to machine code. It's side effect is that source code is not shipped. But what transformation do you expect for string literals (like your key) ?

**Comment by sisou** [comment]
OK, fair enough. Thanks! =)

**Comment by igorklopov** [comment]
:) You are welcome.
